#include <stdint.h>
#include <stdio.h>

int main(void)
{


	// IN THIS CODE I USE PRINTF FOR THAT TYPE OF DEBUGING I NEED TO IMPLEMENT ITM WHICH WE IMPLEMENT IN
	//SYSCALLS.C LINE NO 33 TO 61 . THEN PRINTF IS WRITE VARIABLE THATS WHY WE GIVE THIS TO WRITE IN IN
	//LINE 110 IN THEIR IN FOR LOOP WE GIVE ITM IMPLEMENT FUNCTION AND POINT TO LOCATION
	// THIS IS HOW WE DEBUGU PRINTF IN MCU.


	printf("hello world");
    /* Loop forever */
	for(;;);
}
