/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <stdio.h>

int main(void)
{


	// IN THIS CODE I USE PRINTF FOR THAT TYPE OF DEBUGING I NEED TO IMPLEMENT ITM WHICH WE IMPLEMENT IN
	//SYSCALLS.C LINE NO 33 TO 61 . THEN PRINTF IS WRITE VARIABLE THATS WHY WE GIVE THIS TO WRITE IN IN
	//LINE 110 IN THEIR IN FOR LOOP WE GIVE ITM IMPLEMENT FUNCTION AND POINT TO LOCATION
	// THIS IS HOW WE DEBUGU PRINTF IN MCU.


	printf("hello world");
    /* Loop forever */
	for(;;);
}
